version: '3'
services: 
  web:
    build: .
    volumes: 
      - ./:/var/www/
    networks:
      - network
    depends_on: 
      - db

  db:
    image: postgis/postgis:12-3.4-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laravel
    volumes: 
      - "./.docker/dbdata:/var/lib/postgresql/data"
    networks:
      - network

  nginx:
    build: ./.docker/nginx
    ports:
      - "80:80"
    volumes: 
      - ./:/var/www
    depends_on: 
      - web
    networks:
      - network

networks:
  network:
    driver: bridge
    name: docker_diti